"""initial_schema

Revision ID: 658faa32705f
Revises: 
Create Date: 2026-04-06 06:30:26.965251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '658faa32705f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('NEW_COMMENT', 'COLLAB_REQUEST', 'COLLAB_ACCEPTED', 'COLLAB_DECLINED', 'MILESTONE_POSTED', 'PROJECT_COMPLETED', name='notification_type_enum'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifications_is_read', 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_index('idx_notifications_recipient_id', 'notifications', ['recipient_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stage', sa.Enum('IDEA', 'BUILDING', 'TESTING', 'SHIPPED', 'COMPLETED', name='project_stage_enum'), nullable=False),
    sa.Column('support_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('repo_url', sa.String(length=255), nullable=True),
    sa.Column('live_url', sa.String(length=255), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_completed_at', 'projects', ['completed_at'], unique=False)
    op.create_index('idx_projects_is_public', 'projects', ['is_public'], unique=False)
    op.create_index('idx_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.create_index('idx_projects_stage', 'projects', ['stage'], unique=False)
    op.create_table('celebration_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('shoutout', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('idx_celebration_created_at', 'celebration_entries', ['created_at'], unique=False)
    op.create_index('idx_celebration_featured', 'celebration_entries', ['featured'], unique=False)
    op.create_index('idx_celebration_owner_id', 'celebration_entries', ['owner_id'], unique=False)
    op.create_table('collaboration_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='collab_status_enum'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'requester_id', name='uq_collab_project_requester')
    )
    op.create_index('idx_collab_project_id', 'collaboration_requests', ['project_id'], unique=False)
    op.create_index('idx_collab_requester_id', 'collaboration_requests', ['requester_id'], unique=False)
    op.create_index('idx_collab_status', 'collaboration_requests', ['status'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_author_id', 'comments', ['author_id'], unique=False)
    op.create_index('idx_comments_parent_id', 'comments', ['parent_id'], unique=False)
    op.create_index('idx_comments_project_id', 'comments', ['project_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_milestones_created_at', 'milestones', ['created_at'], unique=False)
    op.create_index('idx_milestones_project_id', 'milestones', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_milestones_project_id', table_name='milestones')
    op.drop_index('idx_milestones_created_at', table_name='milestones')
    op.drop_table('milestones')
    op.drop_index('idx_comments_project_id', table_name='comments')
    op.drop_index('idx_comments_parent_id', table_name='comments')
    op.drop_index('idx_comments_author_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_collab_status', table_name='collaboration_requests')
    op.drop_index('idx_collab_requester_id', table_name='collaboration_requests')
    op.drop_index('idx_collab_project_id', table_name='collaboration_requests')
    op.drop_table('collaboration_requests')
    op.drop_index('idx_celebration_owner_id', table_name='celebration_entries')
    op.drop_index('idx_celebration_featured', table_name='celebration_entries')
    op.drop_index('idx_celebration_created_at', table_name='celebration_entries')
    op.drop_table('celebration_entries')
    op.drop_index('idx_projects_stage', table_name='projects')
    op.drop_index('idx_projects_owner_id', table_name='projects')
    op.drop_index('idx_projects_is_public', table_name='projects')
    op.drop_index('idx_projects_completed_at', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_notifications_recipient_id', table_name='notifications')
    op.drop_index('idx_notifications_is_read', table_name='notifications')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_table('users')

    # Explicitly drop PostgreSQL enums — Alembic does not handle these automatically
    sa.Enum(name='project_stage_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='collab_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='notification_type_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###